[platformio]
src_dir = .

[env:skr14turbo]
platform = nxplpc-arduino-lpc176x
board = nxp_lpc1769
framework = arduino
platform_packages =
  framework-arduino-lpc176x@file://C:/Users/kuzne/.platformio/packages/framework-arduino-lpc176x
build_flags =
  -D__LPC1769__
  -DARDUINO_ARCH_LPC176X
  -DPIO_FRAMEWORK_ARDUINO_LPC176X
build_src_filter =
  +<*.ino>
  +<*.cpp>
  +<src/**>
  -<addons/**>
lib_ldf_mode = chain+
monitor_speed = 9600

[env:skr14turbo_x_motor_test]
platform = nxplpc-arduino-lpc176x
board = nxp_lpc1769
framework = arduino
platform_packages =
  framework-arduino-lpc176x@file://C:/Users/kuzne/.platformio/packages/framework-arduino-lpc176x
build_flags =
  -D__LPC1769__
  -DARDUINO_ARCH_LPC176X
  -DPIO_FRAMEWORK_ARDUINO_LPC176X
build_src_filter =
  -<*>
  +<tools/skr14turbo_x_motor_test.cpp>
lib_ldf_mode = chain+
monitor_speed = 9600

[env:skr14turbo_y_motor_test]
platform = nxplpc-arduino-lpc176x
board = nxp_lpc1769
framework = arduino
platform_packages =
  framework-arduino-lpc176x@file://C:/Users/kuzne/.platformio/packages/framework-arduino-lpc176x
build_flags =
  -D__LPC1769__
  -DARDUINO_ARCH_LPC176X
  -DPIO_FRAMEWORK_ARDUINO_LPC176X
build_src_filter =
  -<*>
  +<tools/skr14turbo_y_motor_test.cpp>
lib_ldf_mode = chain+
monitor_speed = 9600
